server.port=${PORT:8761}
spring.application.name=expense-discovery

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true

eureka.instance.hostname=expense-discovery-xofu.onrender.com
eureka.instance.non-secure-port=443
eureka.instance.prefer-ip-address=false

eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Actuator endpoints
management.endpoints.web.exposure.include=*

eureka.client.service-url.defaultZone=https://expense-discovery-xofu.onrender.com/eureka/

